apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match-service
  template:
    metadata:
      labels:
        app: match-service
      annotations:
        linkerd.io/inject: enabled
    spec:
      serviceAccountName: match-service-sa
      imagePullSecrets:
        - name: craas-4274eb52-inventive-macaw
      containers:
        - name: match-service
          image: 4274eb52-inventive-macaw.registry.twcstorage.ru/tag-duels/match-service-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50001
              name: grpc
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: match-service-env
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: match-kv-credentials
                  key: REDIS_PASSWORD
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            tcpSocket:
              port: 50001
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 50001
            initialDelaySeconds: 5
            periodSeconds: 10
        - name: auth-sidecar
          image: 4274eb52-inventive-macaw.registry.twcstorage.ru/tag-duels/auth-sidecar-server:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: auth-sidecar-env
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"