apiVersion: v1
kind: Service
metadata:
  name: match-service
  namespace: match
spec:
  selector:
    app: match-service
  ports:
    - port: 50001
      targetPort: 50001
      name: grpc
  type: ClusterIP
