apiVersion: v1
kind: Pod
metadata:
  name: rating-service
  namespace: rating
  labels:
    app: rating-service
spec:
  containers:
    - name: rating-service
      image: rating-service-server:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 50001
          name: grpc
      envFrom:
        - configMapRef:
            name: rating-service-env
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: rating-storage-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rating-storage-credentials
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: rating-storage-config
              key: POSTGRES_DB
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
      livenessProbe:
        tcpSocket:
          port: 50001
        initialDelaySeconds: 10
        periodSeconds: 30
      readinessProbe:
        tcpSocket:
          port: 50001
        initialDelaySeconds: 5
        periodSeconds: 10
  restartPolicy: Always
