syntax = "proto3";

package match_history_service;
option go_package = "team_dynamics/api/proto/match_history_service";

message ParticipantData {
    optional uint64 id = 1;
    optional string name = 2;
    optional uint64 rating = 3;
    optional int64 diff = 4;
}

message Round {
    optional bool is_player1_killer = 1;
    optional uint64 time_millis = 2;
}

message MatchData {
    optional ParticipantData player1 = 1;
    optional ParticipantData player2 = 2;
    repeated Round rounds = 3;
    optional uint64 end_timestamp = 4;
}

message GetMatchHistoryRequest {
    optional string pagekey = 1;
}

message GetMatchHistoryResponse {
    repeated MatchData matches = 1;
    optional string pagekey = 2;
}

message SaveMatchRequest {
    optional MatchData match = 1; 
}

message SaveMatchResponse {}

service MatchHistoryService {
    rpc GetMatchHistory(GetMatchHistoryRequest) returns (GetMatchHistoryResponse);
    rpc SaveMatch(SaveMatchRequest) returns (SaveMatchResponse);
}
