syntax = "proto3";

package user_service;
option go_package = "team_dynamics/api/proto/user_service";

import "google/api/annotations.proto";
import "user_common/user_common.proto";

message UserData {
    optional int64 id = 1;
    optional string name = 2;
}

message Friend {
    optional UserData user = 1;
    optional string source = 2;
}

message GetSelfDataRequest {
    optional user_common.ExternalKey key = 1;
}

message GetSelfDataResponse {
    optional UserData user_data = 1;
}

message GetUserDataRequest {
    optional int64 id = 1;
}

message GetUserDataResponse {
    optional UserData user_data = 1;
}

message GetFriendsRequest {
    optional int64 user_id = 1;
    optional string pagekey = 2;
}

message GetFriendsResponse {
    repeated Friend friends = 1;
    optional string pagekey = 2;
}

message GetIncomingRequestsRequest {
    optional int64 user_id = 1;
    optional string pagekey = 2;
}

message GetIncomingRequestsResponse {
    repeated Friend friends = 1;
    optional string pagekey = 2;
}

message GetOutgoingRequestsRequest {
    optional int64 user_id = 1;
    optional string pagekey = 2;
}

message GetOutgoingRequestsResponse {
    repeated Friend friends = 1;
    optional string pagekey = 2;
}

enum AddFriendResult {
    ADD_FRIEND_RESULT_UNSPECIFIED = 0;
    ADD_FRIEND_RESULT_NOOP = 1;
    ADD_FRIEND_RESULT_REQUEST_SENT = 2;
    ADD_FRIEND_RESULT_ACCEPTED = 3;
}

message AddFriendRequest {
    optional int64 user_id = 1;
    optional int64 other_user_id = 2;
}

message AddFriendResponse {
    optional Friend friend = 1;
    AddFriendResult result = 2;
}

enum RemoveFriendResult {
    REMOVE_FRIEND_RESULT_UNSPECIFIED = 0;
    REMOVE_FRIEND_RESULT_NOOP = 1;
    REMOVE_FRIEND_RESULT_REQUEST_CANCELLED = 2;
    REMOVE_FRIEND_RESULT_REQUEST_DECLINED = 3;
    REMOVE_FRIEND_RESULT_FRIEND_REMOVED = 4;
}

message RemoveFriendRequest {
    optional int64 user_id = 1;
    optional int64 other_user_id = 2;
}

message RemoveFriendResponse {
    RemoveFriendResult result = 1;
}

service UserService {
    rpc GetSelfData(GetSelfDataRequest) returns (GetSelfDataResponse) {
        option (google.api.http) = {
            get: "/v1/self"
        };
    }

    rpc GetUserData(GetUserDataRequest) returns (GetUserDataResponse) {
        option (google.api.http) = {
            get: "/v1/users/{id}"
        };
    }

    rpc GetFriends(GetFriendsRequest) returns (GetFriendsResponse) {
        option (google.api.http) = {
            get: "/v1/friends"
        };
    }

    rpc GetIncomingRequests(GetIncomingRequestsRequest) returns (GetIncomingRequestsResponse) {
        option (google.api.http) = {
            get: "/v1/friends/incoming"
        };
    }

    rpc GetOutgoingRequests(GetOutgoingRequestsRequest) returns (GetOutgoingRequestsResponse) {
        option (google.api.http) = {
            get: "/v1/friends/outgoing"
        };
    }

    rpc AddFriend(AddFriendRequest) returns (AddFriendResponse) {
        option (google.api.http) = {
            post: "/v1/friends"
            body: "*"
        };
    }

    rpc RemoveFriend(RemoveFriendRequest) returns (RemoveFriendResponse) {
        option (google.api.http) = {
            post: "/v1/friends/remove"
            body: "*"
        };
    }
}