syntax = "proto3";

package user_service;
option go_package = "team_dynamics/api/proto/user_service";

import "user_common/user_common.proto";

message UserData {
    optional int64 id = 1;
    optional string name = 2;
}

message Friend {
    optional UserData user = 1;
    optional string source = 2;
}

message GetSelfDataRequest {
    optional user_common.ExternalKey key = 1;
}

message GetSelfDataResponse {
    optional UserData user_data = 1;
}

message GetUserDataRequest {
    optional int64 id = 1;
}

message GetUserDataResponse {
    optional UserData user_data = 1;
}

message GetFriendsRequest {
    optional string pagekey = 1;
}

message GetFriendsResponse {
    repeated Friend friends = 1;
    optional string pagekey = 2;
}

message GetIncomingRequestsRequest {
    optional string pagekey = 1;
}

message GetIncomingRequestsResponse {
    repeated Friend friends = 1;
    optional string pagekey = 2;
}

message GetOutgoingRequestsRequest {
    optional string pagekey = 1;
}

message GetOutgoingRequestsResponse {
    repeated Friend friends = 1;
    optional string pagekey = 2;
}

message AddFriendRequest {
    optional int64 user_id = 1;
}

message AddFriendResponse {
    optional Friend friend = 1;
}

service UserService {
    rpc GetSelfData(GetSelfDataRequest) returns (GetSelfDataResponse);
    rpc GetUserData(GetUserDataRequest) returns (GetUserDataResponse);
    rpc GetFriends(GetFriendsRequest) returns (GetFriendsResponse);
    rpc GetIncomingRequests(GetIncomingRequestsRequest) returns (GetIncomingRequestsResponse);
    rpc GetOutgoingRequests(GetOutgoingRequestsRequest) returns (GetOutgoingRequestsResponse);
}
