syntax = "proto3";

package auth_service;
option go_package = "team_dynamics/api/proto/auth_service";

import "google/api/annotations.proto";
import "user_common/user_common.proto";

message AuthExternalRequest {
    optional user_common.ExternalKey external_key = 1;
    optional string auth_token = 2;
}

message AuthExternalResponse {
    optional string access = 1;
    optional string refresh = 2;
}

message RefreshRequest {
    optional string refresh = 1;
}

message RefreshResponse {
    optional string access = 1;
    optional string refresh = 2;
}

message GetPublicKeyRequest {}

message GetPublicKeyResponse {
    optional string primary_public_key = 1;
    optional string secondary_public_key = 2;
    optional string version = 3;
}

service AuthService {
    rpc AuthExternal(AuthExternalRequest) returns (AuthExternalResponse) {
        option (google.api.http) = {
            post: "/v1/auth/external"
            body: "*"
        };
    }
    rpc Refresh(RefreshRequest) returns (RefreshResponse) {
        option (google.api.http) = {
            post: "/v1/auth/refresh"
            body: "*"
        };
    }
    rpc GetPublicKey(GetPublicKeyRequest) returns (GetPublicKeyResponse) {
        option (google.api.http) = {
            get: "/v1/auth/public-key"
        };
    }
}
