apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: fleet1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        is-game-server: "true"
        location: Moscow
    spec:
      ports:
        - name: default
          portPolicy: Dynamic
          containerPort: 7777
      template:
        spec:
          imagePullSecrets:
          - name: craas-4274eb52-inventive-macaw
          containers:
            - name: tag-duels
              image: 4274eb52-inventive-macaw.registry.twcstorage.ru/tag-duels/tag-duels-linux-server:latest
              imagePullPolicy: Always
              resources:
                requests:
                  memory: 3Gi
                  cpu: 1000m
                limits:
                  memory: 4Gi
                  cpu: 2000m
