apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: tag-duels-autoscaler
spec:
  fleetName: fleet1
  policy:
    type: Buffer
    buffer:
      bufferSize: 2
      minReplicas: 2
      maxReplicas: 10