apiVersion: apps/v1
kind: Deployment
metadata:
  name: mm-event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mm-event
  template:
    metadata:
      labels:
        app: mm-event
      annotations:
        linkerd.io/inject: enabled
    spec:
      serviceAccountName: mm-event-sa
      imagePullSecrets:
        - name: craas-4274eb52-inventive-macaw
      containers:
        - name: mm-event
          image: 4274eb52-inventive-macaw.registry.twcstorage.ru/tag-duels/mm-event-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: websockets
          envFrom:
            - configMapRef:
                name: mm-event-env
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mm-pool-credentials
                  key: REDIS_PASSWORD
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            tcpSocket:
              port: 50001
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 50001
            initialDelaySeconds: 5
            periodSeconds: 10
        - name: auth-sidecar
          image: 4274eb52-inventive-macaw.registry.twcstorage.ru/tag-duels/auth-sidecar-server:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: auth-sidecar-env
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"