apiVersion: v1
kind: Pod
metadata:
  name: mm-event
  namespace: matchmaking
  labels:
    app: mm-event
spec:
  containers:
    - name: mm-event
      image: mm-event-server:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 50001
          name: grpc
      envFrom:
        - configMapRef:
            name: mm-event-env
      env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mm-pool-credentials
              key: REDIS_PASSWORD
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
      livenessProbe:
        tcpSocket:
          port: 50001
        initialDelaySeconds: 10
        periodSeconds: 30
      readinessProbe:
        tcpSocket:
          port: 50001
        initialDelaySeconds: 5
        periodSeconds: 10
  restartPolicy: Always
