apiVersion: v1
kind: Service
metadata:
  name: mm-event
  namespace: matchmaking
spec:
  selector:
    app: mm-event
  ports:
    - port: 50001
      targetPort: 50001
      name: grpc
  type: ClusterIP
