apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: match-history-service-auth-sidecar-rolebinding
subjects:
  - kind: ServiceAccount
    name: match-history-service-sa
roleRef:
  kind: ClusterRole
  name: auth-sidecar-role
  apiGroup: rbac.authorization.k8s.io
