apiVersion: v1
kind: Service
metadata:
  name: match-history-service-service
  namespace: match-history
spec:
  selector:
    app: match-history-service
  ports:
    - port: 50001
      targetPort: 50001
      name: grpc
  type: ClusterIP