apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
      annotations:
        linkerd.io/inject: enabled
    spec:
      imagePullSecrets:
        - name: craas-4274eb52-inventive-macaw
      containers:
        - name: user-service
          image: 4274eb52-inventive-macaw.registry.twcstorage.ru/tag-duels/user-service-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50001
              name: grpc
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: user-service-env
          env:
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: user-storage-credentials
                  key: POSTGRES_USER
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-storage-credentials
                  key: POSTGRES_PASSWORD
            - name: PG_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: user-storage-config
                  key: POSTGRES_DB
            - name: STEAM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: steam-api
                  key: API_KEY
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            tcpSocket:
              port: 50001
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 50001
            initialDelaySeconds: 5
            periodSeconds: 10