apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  namespace: user
spec:
  selector:
    app: user-service
  ports:
    - port: 50001
      targetPort: 50001
      name: grpc
  type: ClusterIP