apiVersion: v1
kind: Service
metadata:
  name: match-history-service-v2
spec:
  selector:
    app: match-history-service-v2
  ports:
    - port: 50001
      targetPort: 50001
      name: grpc
  type: ClusterIP
