syntax = "proto3";

package rating_service;
option go_package = "api/proto/user_service";

message RatingData {
    optional double rating_value = 1;
    optional double rating_distribution = 2;
    optional uint64 display_value = 3;
}

message GetRatingRequest {
    optional uint64 user_id = 1;
}

message GetRatingResponse {
    optional RatingData rating = 1;
}

message UpdateRatingRequest {
    optional uint64 winner_id = 1;
    optional uint64 loser_id = 2;
    optional RatingData winner_rating = 3;
    optional RatingData loser_rating = 4;
}

message UpdateRatingResponse {
    optional RatingData winner_rating = 1;
    optional RatingData loser_rating = 2;
    optional int64 winner_diff = 3;
    optional int64 loser_diff = 4;
}

service RatingService {
    rpc GetRating(GetRatingRequest) returns (GetRatingResponse);
    rpc UpdateRating(UpdateRatingRequest) returns (UpdateRatingResponse);
}
