;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="PlayerInput.Movement.Moving",NewTagName="PlayerInput.Movement.Move")
+GameplayTagRedirects=(OldTagName="Abilities.Interact",NewTagName="Abilities.LocalInteract")
+GameplayTagList=(Tag="Abilities.Attack",DevComment="")
+GameplayTagList=(Tag="Abilities.Attack.Recovery",DevComment="")
+GameplayTagList=(Tag="Abilities.GetStunned",DevComment="")
+GameplayTagList=(Tag="Abilities.LocalInteract",DevComment="")
+GameplayTagList=(Tag="Abilities.LockIn",DevComment="")
+GameplayTagList=(Tag="Abilities.Movement",DevComment="")
+GameplayTagList=(Tag="Abilities.Movement.Crouch",DevComment="")
+GameplayTagList=(Tag="Abilities.Movement.Move",DevComment="")
+GameplayTagList=(Tag="Abilities.Movement.Sprint",DevComment="")
+GameplayTagList=(Tag="Abilities.PalletBreak",DevComment="")
+GameplayTagList=(Tag="Abilities.PalletDrop",DevComment="")
+GameplayTagList=(Tag="Abilities.RemoveTagOrAttribute",DevComment="")
+GameplayTagList=(Tag="Abilities.RemoveTagOrAttribute.Haste",DevComment="")
+GameplayTagList=(Tag="Abilities.RemoveTagOrAttribute.Hinder",DevComment="")
+GameplayTagList=(Tag="Abilities.Vault",DevComment="")
+GameplayTagList=(Tag="Cooldowns.Attack",DevComment="")
+GameplayTagList=(Tag="Data.Duration",DevComment="")
+GameplayTagList=(Tag="Data.Haste",DevComment="")
+GameplayTagList=(Tag="Data.Hinder",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Attack",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Attack.Ended",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Attack.Hit",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Attack.Recovery",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Attack.Started",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.DropPallet",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.GetStunned",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.GetStunned.ClientSided",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.LocalInteract",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.LocalInteract.Release",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.LockIn",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.LockIn.Cancel",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Movement.Crouch",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Movement.Crouch.Ended",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Movement.Crouch.Started",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Movement.Move",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Movement.Move.Ended",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Movement.Move.Started",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Movement.Sprint",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Movement.Sprint.Ended",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Movement.Sprint.Started",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.RemoveTagOrAttribute",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.RemoveTagOrAttribute.Haste",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.RemoveTagOrAttribute.Hinder",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Test",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Vault",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Vault.Cancel",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Vault.Fast",DevComment="")
+GameplayTagList=(Tag="Event.AnimNotify",DevComment="")
+GameplayTagList=(Tag="Event.AnimNotify.AttackPause",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Hunter",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Prey",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Sound.FastVault",DevComment="")
+GameplayTagList=(Tag="Interactables.State.InUse",DevComment="")
+GameplayTagList=(Tag="State.Incapacitated",DevComment="")
+GameplayTagList=(Tag="State.Locked",DevComment="")
+GameplayTagList=(Tag="State.Movement",DevComment="")
+GameplayTagList=(Tag="State.Movement.Crouching",DevComment="")
+GameplayTagList=(Tag="State.Movement.Moving",DevComment="")
+GameplayTagList=(Tag="State.Movement.Sprinting",DevComment="")
+GameplayTagList=(Tag="State.Stunned",DevComment="")
+GameplayTagList=(Tag="State.Vaulting",DevComment="")

