// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: proto/fleet_manager.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllocateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player1       *uint64                `protobuf:"varint,1,opt,name=player1,proto3,oneof" json:"player1,omitempty"`
	Player2       *uint64                `protobuf:"varint,2,opt,name=player2,proto3,oneof" json:"player2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateRequest) Reset() {
	*x = AllocateRequest{}
	mi := &file_proto_fleet_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateRequest) ProtoMessage() {}

func (x *AllocateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleet_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateRequest.ProtoReflect.Descriptor instead.
func (*AllocateRequest) Descriptor() ([]byte, []int) {
	return file_proto_fleet_manager_proto_rawDescGZIP(), []int{0}
}

func (x *AllocateRequest) GetPlayer1() uint64 {
	if x != nil && x.Player1 != nil {
		return *x.Player1
	}
	return 0
}

func (x *AllocateRequest) GetPlayer2() uint64 {
	if x != nil && x.Player2 != nil {
		return *x.Player2
	}
	return 0
}

type AllocateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *string                `protobuf:"bytes,1,opt,name=address,proto3,oneof" json:"address,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateResponse) Reset() {
	*x = AllocateResponse{}
	mi := &file_proto_fleet_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateResponse) ProtoMessage() {}

func (x *AllocateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleet_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateResponse.ProtoReflect.Descriptor instead.
func (*AllocateResponse) Descriptor() ([]byte, []int) {
	return file_proto_fleet_manager_proto_rawDescGZIP(), []int{1}
}

func (x *AllocateResponse) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *AllocateResponse) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type GetServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerRequest) Reset() {
	*x = GetServerRequest{}
	mi := &file_proto_fleet_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerRequest) ProtoMessage() {}

func (x *GetServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleet_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerRequest.ProtoReflect.Descriptor instead.
func (*GetServerRequest) Descriptor() ([]byte, []int) {
	return file_proto_fleet_manager_proto_rawDescGZIP(), []int{2}
}

func (x *GetServerRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type GetServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *string                `protobuf:"bytes,1,opt,name=address,proto3,oneof" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerResponse) Reset() {
	*x = GetServerResponse{}
	mi := &file_proto_fleet_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerResponse) ProtoMessage() {}

func (x *GetServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleet_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerResponse.ProtoReflect.Descriptor instead.
func (*GetServerResponse) Descriptor() ([]byte, []int) {
	return file_proto_fleet_manager_proto_rawDescGZIP(), []int{3}
}

func (x *GetServerResponse) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

var File_proto_fleet_manager_proto protoreflect.FileDescriptor

const file_proto_fleet_manager_proto_rawDesc = "" +
	"\n" +
	"\x19proto/fleet_manager.proto\"g\n" +
	"\x0fAllocateRequest\x12\x1d\n" +
	"\aplayer1\x18\x01 \x01(\x04H\x00R\aplayer1\x88\x01\x01\x12\x1d\n" +
	"\aplayer2\x18\x02 \x01(\x04H\x01R\aplayer2\x88\x01\x01B\n" +
	"\n" +
	"\b_player1B\n" +
	"\n" +
	"\b_player2\"_\n" +
	"\x10AllocateResponse\x12\x1d\n" +
	"\aaddress\x18\x01 \x01(\tH\x00R\aaddress\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01B\n" +
	"\n" +
	"\b_addressB\a\n" +
	"\x05_name\"4\n" +
	"\x10GetServerRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\">\n" +
	"\x11GetServerResponse\x12\x1d\n" +
	"\aaddress\x18\x01 \x01(\tH\x00R\aaddress\x88\x01\x01B\n" +
	"\n" +
	"\b_address2s\n" +
	"\fFleetManager\x12/\n" +
	"\bAllocate\x12\x10.AllocateRequest\x1a\x11.AllocateResponse\x122\n" +
	"\tGetServer\x12\x11.GetServerRequest\x1a\x12.GetServerResponseB\x15Z\x13fleet_manager/protob\x06proto3"

var (
	file_proto_fleet_manager_proto_rawDescOnce sync.Once
	file_proto_fleet_manager_proto_rawDescData []byte
)

func file_proto_fleet_manager_proto_rawDescGZIP() []byte {
	file_proto_fleet_manager_proto_rawDescOnce.Do(func() {
		file_proto_fleet_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fleet_manager_proto_rawDesc), len(file_proto_fleet_manager_proto_rawDesc)))
	})
	return file_proto_fleet_manager_proto_rawDescData
}

var file_proto_fleet_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_fleet_manager_proto_goTypes = []any{
	(*AllocateRequest)(nil),   // 0: AllocateRequest
	(*AllocateResponse)(nil),  // 1: AllocateResponse
	(*GetServerRequest)(nil),  // 2: GetServerRequest
	(*GetServerResponse)(nil), // 3: GetServerResponse
}
var file_proto_fleet_manager_proto_depIdxs = []int32{
	0, // 0: FleetManager.Allocate:input_type -> AllocateRequest
	2, // 1: FleetManager.GetServer:input_type -> GetServerRequest
	1, // 2: FleetManager.Allocate:output_type -> AllocateResponse
	3, // 3: FleetManager.GetServer:output_type -> GetServerResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_fleet_manager_proto_init() }
func file_proto_fleet_manager_proto_init() {
	if File_proto_fleet_manager_proto != nil {
		return
	}
	file_proto_fleet_manager_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_fleet_manager_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_fleet_manager_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_fleet_manager_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fleet_manager_proto_rawDesc), len(file_proto_fleet_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fleet_manager_proto_goTypes,
		DependencyIndexes: file_proto_fleet_manager_proto_depIdxs,
		MessageInfos:      file_proto_fleet_manager_proto_msgTypes,
	}.Build()
	File_proto_fleet_manager_proto = out.File
	file_proto_fleet_manager_proto_goTypes = nil
	file_proto_fleet_manager_proto_depIdxs = nil
}
