apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    environment: dev
  name: match-history-storage-pvc
  namespace: match-history
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
