apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    environment: dev
  name: match-history-storage-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
