apiVersion: v1
kind: ConfigMap
metadata:
  name: match-history-storage-init
  namespace: match-history
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS matches (
        match_id TEXT PRIMARY KEY,
        player1_id BIGINT,
        player2_id BIGINT,
        player1_name TEXT,
        player2_name TEXT,
        player1_rating BIGINT,
        player2_rating BIGINT,
        end_timestamp timestamptz,
        result INT
    );
    
    CREATE TABLE IF NOT EXISTS rounds (
        match_id TEXT,
        round_number BIGINT,
        is_player1_killer BOOLEAN,
        time_millis BIGINT,
        PRIMARY KEY (match_id, round_number),
        FOREIGN KEY (match_id) REFERENCES matches(match_id)
    );
    
    CREATE INDEX IF NOT EXISTS idx_matches_player1_timestamp ON matches (player1_id, end_timestamp DESC);
    CREATE INDEX IF NOT EXISTS idx_matches_player2_timestamp ON matches (player2_id, end_timestamp DESC);
