apiVersion: v1
kind: ConfigMap
metadata:
  name: user-storage-init
  namespace: user
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
        id BIGINT PRIMARY KEY,
        name TEXT,
        steam_id BIGINT UNIQUE
    );
