apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    environment: production
  name: rating-storage-pvc
  namespace: rating
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
