package services

import (
	"context"
	"errors"
	"fmt"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"strconv"
	"sync"
	fmPb "team_dynamics/api/proto/fleet_manager"
	mhsPb "team_dynamics/api/proto/match_history_service"
	pb "team_dynamics/api/proto/match_service"
	rsPb "team_dynamics/api/proto/rating_service"
	"team_dynamics/logging"
	"team_dynamics/match_service/models"
	"team_dynamics/match_service/redis"
	"time"
)

type MatchService interface {
	StartMatch(ctx context.Context, request *pb.StartMatchRequest) (*pb.StartMatchResponse, error)
	GetMatch(ctx context.Context, request *pb.GetMatchRequest) (*pb.GetMatchResponse, error)
	EndMatch(ctx context.Context, request *pb.EndMatchRequest) (*pb.EndMatchResponse, error)
	CancelMatch(ctx context.Context, request *pb.CancelMatchRequest) (*pb.CancelMatchResponse, error)
	RenewMatch(ctx context.Context, request *pb.RenewMatchRequest) (*pb.RenewMatchResponse, error)
}

type matchServiceImpl struct {
	repo      redis.MatchKvRepo
	fmClient  fmPb.FleetManagerClient
	rsClient  rsPb.RatingServiceClient
	mhsClient mhsPb.MatchHistoryServiceClient
}

func MakeMatchService(repo redis.MatchKvRepo, fmClient fmPb.FleetManagerClient, rsClient rsPb.RatingServiceClient, mhsClient mhsPb.MatchHistoryServiceClient) MatchService {
	return &matchServiceImpl{repo, fmClient, rsClient, mhsClient}
}

func validatePlayerData(data *pb.PlayerData) error {
	if data == nil {
		return errors.New("no player data")
	}
	if data.PlayerId == nil {
		return errors.New("no player_id")
	}
	if data.PlayerName == nil {
		return errors.New("no player_name")
	}
	if data.PlayerRating == nil {
		return errors.New("no player_rating")
	}
	if data.RegId == nil {
		return errors.New("no reg_id")
	}
	return nil
}

func validateInputMatch(match *pb.InputMatch, idx int) error {
	if match == nil {
		return fmt.Errorf("input match %d is nil", idx)
	}
	if match.Fleet == nil || *match.Fleet == "" {
		return fmt.Errorf("input match %d: no fleet", idx)
	}
	if err := validatePlayerData(match.Player1); err != nil {
		return fmt.Errorf("input match %d player1: %w", idx, err)
	}
	if err := validatePlayerData(match.Player2); err != nil {
		return fmt.Errorf("input match %d player2: %w", idx, err)
	}
	return nil
}

func mapFailResponse(f models.PlayerFailResponse) pb.PlayerFailResponse {
	switch f {
	case models.REENTER:
		return pb.PlayerFailResponse_PLAYER_FAIL_RESPONSE_REENTER
	case models.REMOVE:
		return pb.PlayerFailResponse_PLAYER_FAIL_RESPONSE_REMOVE
	default:
		return pb.PlayerFailResponse_PLAYER_FAIL_RESPONSE_UNSPECIFIED
	}
}

func validateGetMatchRequest(req *pb.GetMatchRequest) error {
	if req == nil {
		return errors.New("request is nil")
	}
	if req.PlayerId == nil {
		return errors.New("player_id is required")
	}
	return nil
}

func validateEndMatchRequest(req *pb.EndMatchRequest) error {
	if req == nil {
		return errors.New("request is nil")
	}
	if req.MatchId == nil || *req.MatchId == "" {
		return errors.New("match_id is required")
	}
	return nil
}

func validateCancelMatchRequest(req *pb.CancelMatchRequest) error {
	if req == nil {
		return errors.New("request is nil")
	}
	if req.MatchId == nil || *req.MatchId == "" {
		return errors.New("match_id is required")
	}
	return nil
}

func validateRenewMatchRequest(req *pb.RenewMatchRequest) error {
	if req == nil {
		return errors.New("request is nil")
	}
	if req.MatchId == nil || *req.MatchId == "" {
		return errors.New("match_id is required")
	}
	return nil
}

func (s *matchServiceImpl) StartMatch(ctx context.Context, request *pb.StartMatchRequest) (*pb.StartMatchResponse, error) {
	logger := logging.GetLogger(ctx)

	// Validate request
	if request == nil {
		logger.Debug("StartMatch: request is nil")
		return nil, status.Error(codes.InvalidArgument, "request is nil")
	}
	for i, match := range request.Matches {
		if err := validateInputMatch(match, i); err != nil {
			logger.Debug("StartMatch: validation failed", "index", i, "error", err)
			return nil, status.Errorf(codes.InvalidArgument, "invalid input match %d: %v", i, err)
		}
	}

	results := make([]*pb.MatchCreationResult, 0, len(request.Matches))

	for _, input := range request.Matches {
		// Build models.Player from proto PlayerData
		player1 := models.Player{
			Id:     *input.Player1.PlayerId,
			Name:   *input.Player1.PlayerName,
			Rating: *input.Player1.PlayerRating,
			RegId:  *input.Player1.RegId,
		}
		player2 := models.Player{
			Id:     *input.Player2.PlayerId,
			Name:   *input.Player2.PlayerName,
			Rating: *input.Player2.PlayerRating,
			RegId:  *input.Player2.RegId,
		}

		// Build models.Match (MatchId will be generated by repo, Status will be set by repo)
		match := models.Match{
			Player1Id: player1.Id,
			Player2Id: player2.Id,
			Fleet:     *input.Fleet,
		}

		// Call repo
		result, err := s.repo.SaveCreateMatch(ctx, match, player1, player2)
		if err != nil {
			logger.Debug("StartMatch: SaveCreateMatch failed", "error", err, "result", result)
			results = append(results, &pb.MatchCreationResult{
				MatchId:             nil,
				Player1FailResponse: pb.PlayerFailResponse_PLAYER_FAIL_RESPONSE_REENTER,
				Player2FailResponse: pb.PlayerFailResponse_PLAYER_FAIL_RESPONSE_REENTER,
			})
			continue
		}

		// Success
		res := &pb.MatchCreationResult{
			MatchId: result.MatchId,
		}
		if result.Fail1 != nil {
			res.Player1FailResponse = mapFailResponse(*result.Fail1)
		}
		if result.Fail2 != nil {
			res.Player2FailResponse = mapFailResponse(*result.Fail2)
		}
		results = append(results, res)
	}

	return &pb.StartMatchResponse{Results: results}, nil
}

func (s *matchServiceImpl) GetMatch(ctx context.Context, request *pb.GetMatchRequest) (*pb.GetMatchResponse, error) {
	logger := logging.GetLogger(ctx)

	if err := validateGetMatchRequest(request); err != nil {
		logger.Debug("GetMatch: validation failed", "error", err)
		return nil, status.Error(codes.InvalidArgument, err.Error())
	}
	match, player1, player2, err := s.repo.GetMatchByPlayerId(ctx, *request.PlayerId)
	if err != nil {
		logger.Debug("GetMatch: GetMatchByPlayerId failed", "playerId", *request.PlayerId, "error", err)
		return nil, status.Errorf(codes.Internal, "failed to get match: %v", err)
	}
	if match == nil {
		logger.Debug("GetMatch: no match found for player", "playerId", *request.PlayerId)
		return &pb.GetMatchResponse{}, nil
	}
	switch match.Status {
	case models.Finished:
		logger.Debug("GetMatch: match finished, removing", "matchId", match.MatchId)
		if err := s.repo.RemoveMatch(ctx, match.MatchId); err != nil {
			logger.Debug("GetMatch: RemoveMatch failed", "matchId", match.MatchId, "error", err)
			return nil, status.Errorf(codes.Internal, "failed to remove finished match: %v", err)
		}
		return &pb.GetMatchResponse{}, nil

	case models.Ongoing:
		// Query fleet manager for server connection
		req := &fmPb.GetServerRequest{
			MatchId: &match.MatchId,
		}
		resp, err := s.fmClient.GetServer(ctx, req)
		if err != nil {
			logger.Debug("GetMatch: GetServer failed or no connection info", "matchId", match.MatchId, "error", err)
			return &pb.GetMatchResponse{}, nil
		}
		if resp == nil || resp.ConnectionInfo == nil {
			logger.Warn("GetMatch: server for ongoing match not found - clearing")
			if err := s.repo.RemoveMatch(ctx, match.MatchId); err != nil {
				logger.Warn("GetMatch: unable to remove absent ongoing match from redis", "error", err)
			}
			return &pb.GetMatchResponse{}, nil
		}
		return &pb.GetMatchResponse{
			ConnectionInfo: resp.ConnectionInfo,
		}, nil

	case models.Requested:
		// Prepare player annotations
		player1IdStr := strconv.FormatInt(player1.Id, 10)
		player1Name := player1.Name
		player1RatingStr := strconv.FormatInt(player1.Rating, 10)

		player2IdStr := strconv.FormatInt(player2.Id, 10)
		player2Name := player2.Name
		player2RatingStr := strconv.FormatInt(player2.Rating, 10)

		allocReq := &fmPb.AllocateRequest{
			Player1: &fmPb.PlayerAnnotations{
				Id:     &player1IdStr,
				Name:   &player1Name,
				Rating: &player1RatingStr,
			},
			Player2: &fmPb.PlayerAnnotations{
				Id:     &player2IdStr,
				Name:   &player2Name,
				Rating: &player2RatingStr,
			},
			FleetName: &match.Fleet,
			MatchId:   &match.MatchId,
		}
		allocResp, err := s.fmClient.Allocate(ctx, allocReq)
		if err != nil || allocResp == nil || allocResp.ConnectionInfo == nil {
			logger.Debug("GetMatch: Allocate failed or no connection info", "matchId", match.MatchId, "error", err)
			return &pb.GetMatchResponse{}, nil
		}
		// Mark match as started
		if err := s.repo.SaveMatchStart(ctx, match.MatchId); err != nil {
			logger.Debug("GetMatch: SaveMatchStart failed", "matchId", match.MatchId, "error", err)
			return nil, status.Errorf(codes.Internal, "failed to update match status: %v", err)
		}
		return &pb.GetMatchResponse{
			ConnectionInfo: allocResp.ConnectionInfo,
		}, nil

	default:
		logger.Debug("GetMatch: unknown match status", "matchId", match.MatchId, "status", match.Status)
		return &pb.GetMatchResponse{}, nil
	}
}

func (s *matchServiceImpl) EndMatch(ctx context.Context, request *pb.EndMatchRequest) (*pb.EndMatchResponse, error) {
	logger := logging.GetLogger(ctx)

	if err := validateEndMatchRequest(request); err != nil {
		logger.Debug("EndMatch: validation failed", "error", err)
		return nil, status.Error(codes.InvalidArgument, err.Error())
	}

	// Retrieve match and players by match id
	match, player1, player2, err := s.repo.GetMatchById(ctx, *request.MatchId)
	if err != nil {
		logger.Debug("EndMatch: GetMatchById failed", "matchId", *request.MatchId, "error", err)
		return &pb.EndMatchResponse{}, nil
	}
	if match == nil {
		logger.Debug("EndMatch: match not found", "matchId", *request.MatchId)
		return &pb.EndMatchResponse{}, nil
	}

	// Only ongoing matches can be ended
	if match.Status != models.Ongoing {
		logger.Debug("EndMatch: match not ongoing", "matchId", match.MatchId, "status", match.Status)
		return &pb.EndMatchResponse{}, nil
	}

	// Determine match outcome
	var result rsPb.MatchResult
	var historyResult mhsPb.MatchResult
	if request.WinnerId == nil {
		// Draw
		result = rsPb.MatchResult_MATCH_RESULT_DRAW
		historyResult = mhsPb.MatchResult_MATCH_RESULT_DRAW
	} else {
		winnerId := *request.WinnerId
		switch winnerId {
		case player1.Id:
			result = rsPb.MatchResult_MATCH_RESULT_WINNER
			historyResult = mhsPb.MatchResult_MATCH_RESULT_PLAYER1_WIN
		case player2.Id:
			result = rsPb.MatchResult_MATCH_RESULT_LOSER
			historyResult = mhsPb.MatchResult_MATCH_RESULT_PLAYER2_WIN
		default:
			logger.Debug("EndMatch: winner_id does not match any player", "winnerId", winnerId, "player1Id", player1.Id, "player2Id", player2.Id)
			return nil, status.Error(codes.InvalidArgument, "winner_id does not match either player")
		}
	}

	// Prepare rating service request
	ratingReq := &rsPb.UpdateRatingRequest{
		Player1Id:   &player1.Id,
		Player2Id:   &player2.Id,
		MatchResult: result,
		MatchId:     &match.MatchId,
	}

	// Prepare match history request
	nowMillis := time.Now().UnixMilli()
	endTimestamp := nowMillis
	p1Data := &mhsPb.ParticipantData{
		Id:     &player1.Id,
		Name:   &player1.Name,
		Rating: &player1.Rating,
	}
	p2Data := &mhsPb.ParticipantData{
		Id:     &player2.Id,
		Name:   &player2.Name,
		Rating: &player2.Rating,
	}
	matchData := &mhsPb.MatchData{
		Player1:      p1Data,
		Player2:      p2Data,
		Rounds:       []*mhsPb.Round{},
		EndTimestamp: &endTimestamp,
		MatchResult:  historyResult,
		MatchId:      &match.MatchId,
	}
	historyReq := &mhsPb.SaveMatchRequest{
		Match: matchData,
	}

	// Call both services concurrently
	var ratingErr, historyErr error
	var wg sync.WaitGroup
	wg.Add(2)

	go func() {
		defer wg.Done()
		_, ratingErr = s.rsClient.UpdateRating(ctx, ratingReq)
	}()
	go func() {
		defer wg.Done()
		_, historyErr = s.mhsClient.SaveMatch(ctx, historyReq)
	}()

	wg.Wait()

	// If either fails, return conflict error
	if ratingErr != nil || historyErr != nil {
		logger.Debug("EndMatch: downstream service error", "ratingErr", ratingErr, "historyErr", historyErr)
		return nil, status.Errorf(codes.Aborted, "failed to record match result: rating error=%v, history error=%v", ratingErr, historyErr)
	}

	// Mark match as finished in Redis
	if err := s.repo.SaveMatchFinish(ctx, match.MatchId); err != nil {
		logger.Debug("EndMatch: SaveMatchFinish failed", "matchId", match.MatchId, "error", err)
		return nil, status.Errorf(codes.Aborted, "failed to update match status: %v", err)
	}

	return &pb.EndMatchResponse{}, nil
}

func (s *matchServiceImpl) CancelMatch(ctx context.Context, request *pb.CancelMatchRequest) (*pb.CancelMatchResponse, error) {
	logger := logging.GetLogger(ctx)

	if err := validateCancelMatchRequest(request); err != nil {
		logger.Debug("CancelMatch: validation failed", "error", err)
		return nil, status.Error(codes.InvalidArgument, err.Error())
	}

	// Retrieve match and players by match id
	match, player1, player2, err := s.repo.GetMatchById(ctx, *request.MatchId)
	if err != nil || match == nil {
		logger.Debug("CancelMatch: match not found or error", "matchId", *request.MatchId, "error", err)
		return &pb.CancelMatchResponse{}, nil
	}

	// Build match history request with cancelled status
	nowMillis := time.Now().UnixMilli()
	p1Data := &mhsPb.ParticipantData{
		Id:     &player1.Id,
		Name:   &player1.Name,
		Rating: &player1.Rating,
	}
	p2Data := &mhsPb.ParticipantData{
		Id:     &player2.Id,
		Name:   &player2.Name,
		Rating: &player2.Rating,
	}
	matchData := &mhsPb.MatchData{
		Player1:      p1Data,
		Player2:      p2Data,
		Rounds:       []*mhsPb.Round{},
		EndTimestamp: &nowMillis,
		MatchResult:  mhsPb.MatchResult_MATCH_RESULT_CANCELLED,
		MatchId:      &match.MatchId,
	}
	historyReq := &mhsPb.SaveMatchRequest{
		Match: matchData,
	}

	// Save cancelled match to history
	_, err = s.mhsClient.SaveMatch(ctx, historyReq)
	if err != nil {
		logger.Debug("CancelMatch: SaveMatch failed", "matchId", match.MatchId, "error", err)
		return nil, status.Errorf(codes.Aborted, "failed to save cancelled match to history: %v", err)
	}

	// Remove match from Redis
	if err := s.repo.RemoveMatch(ctx, match.MatchId); err != nil {
		logger.Debug("CancelMatch: RemoveMatch failed", "matchId", match.MatchId, "error", err)
		return nil, status.Errorf(codes.Aborted, "failed to remove match: %v", err)
	}

	return &pb.CancelMatchResponse{}, nil
}

func (s *matchServiceImpl) RenewMatch(ctx context.Context, request *pb.RenewMatchRequest) (*pb.RenewMatchResponse, error) {
	logger := logging.GetLogger(ctx)

	if err := validateRenewMatchRequest(request); err != nil {
		logger.Debug("RenewMatch: validation failed", "error", err)
		return nil, status.Error(codes.InvalidArgument, err.Error())
	}

	if err := s.repo.RestartMatch(ctx, *request.MatchId); err != nil {
		logger.Debug("RenewMatch: RestartMatch failed", "matchId", *request.MatchId, "error", err)
		return nil, status.Errorf(codes.Aborted, "failed to renew match: %v", err)
	}

	return &pb.RenewMatchResponse{}, nil
}
