package services

import (
	"context"
	"errors"
	"fmt"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"sync"
	fmPb "team_dynamics/api/proto/fleet_manager"
	v2Pb "team_dynamics/api/proto/match_history_service_v2"
	pb "team_dynamics/api/proto/match_service"
	"team_dynamics/logging"
	"team_dynamics/match_service/downstream"
	"team_dynamics/match_service/models"
	"team_dynamics/match_service/redis"
	"strconv"
	"time"
)

type MatchService interface {
	StartMatch(ctx context.Context, request *pb.StartMatchRequest) (*pb.StartMatchResponse, error)
	GetMatch(ctx context.Context, request *pb.GetMatchRequest) (*pb.GetMatchResponse, error)
	EndMatch(ctx context.Context, request *pb.EndMatchRequest) (*pb.EndMatchResponse, error)
	CancelMatch(ctx context.Context, request *pb.CancelMatchRequest) (*pb.CancelMatchResponse, error)
	RenewMatch(ctx context.Context, request *pb.RenewMatchRequest) (*pb.RenewMatchResponse, error)
}

type matchServiceImpl struct {
	repo        redis.MatchKvRepo
	fmFactory   downstream.FleetManagerClientFactory
	mhsV2Factory downstream.MatchHistoryServiceV2ClientFactory
}

func MakeMatchService(repo redis.MatchKvRepo, fmFactory downstream.FleetManagerClientFactory, mhsV2Factory downstream.MatchHistoryServiceV2ClientFactory) MatchService {
	return &matchServiceImpl{repo, fmFactory, mhsV2Factory}
}

func validatePlayerData(data *pb.PlayerData) error {
	if data == nil {
		return errors.New("no player data")
	}
	if data.PlayerId == nil {
		return errors.New("no player_id")
	}
	if data.PlayerName == nil {
		return errors.New("no player_name")
	}
	if data.PlayerRating == nil {
		return errors.New("no player_rating")
	}
	if data.RegId == nil {
		return errors.New("no reg_id")
	}
	return nil
}

func validateInputMatch(match *pb.InputMatch, idx int) error {
	if match == nil {
		return fmt.Errorf("input match %d is nil", idx)
	}
	if err := validatePlayerData(match.Player1); err != nil {
		return fmt.Errorf("input match %d player1: %w", idx, err)
	}
	if err := validatePlayerData(match.Player2); err != nil {
		return fmt.Errorf("input match %d player2: %w", idx, err)
	}
	return nil
}

func mapFailResponse(f models.PlayerFailResponse) pb.PlayerFailResponse {
	switch f {
	case models.REENTER:
		return pb.PlayerFailResponse_PLAYER_FAIL_RESPONSE_REENTER
	case models.REMOVE:
		return pb.PlayerFailResponse_PLAYER_FAIL_RESPONSE_REMOVE
	default:
		return pb.PlayerFailResponse_PLAYER_FAIL_RESPONSE_UNSPECIFIED
	}
}

func validateGetMatchRequest(req *pb.GetMatchRequest) error {
	if req == nil {
		return errors.New("request is nil")
	}
	if req.PlayerId == nil {
		return errors.New("player_id is required")
	}
	return nil
}

func validateEndMatchRequest(req *pb.EndMatchRequest) error {
	if req == nil {
		return errors.New("request is nil")
	}
	if req.MatchId == nil || *req.MatchId == "" {
		return errors.New("match_id is required")
	}
	return nil
}

func validateCancelMatchRequest(req *pb.CancelMatchRequest) error {
	if req == nil {
		return errors.New("request is nil")
	}
	if req.MatchId == nil || *req.MatchId == "" {
		return errors.New("match_id is required")
	}
	return nil
}

func validateRenewMatchRequest(req *pb.RenewMatchRequest) error {
	if req == nil {
		return errors.New("request is nil")
	}
	if req.MatchId == nil || *req.MatchId == "" {
		return errors.New("match_id is required")
	}
	return nil
}

func (s *matchServiceImpl) StartMatch(ctx context.Context, request *pb.StartMatchRequest) (*pb.StartMatchResponse, error) {
	logger := logging.GetLogger(ctx)

	// Validate request
	if request == nil {
		logger.Debug("StartMatch: request is nil")
		return nil, status.Error(codes.InvalidArgument, "request is nil")
	}
	for i, match := range request.Matches {
		if err := validateInputMatch(match, i); err != nil {
			logger.Debug("StartMatch: validation failed", "index", i, "error", err)
			return nil, status.Errorf(codes.InvalidArgument, "invalid input match %d: %v", i, err)
		}
	}

	results := make([]*pb.MatchCreationResult, 0, len(request.Matches))

	for _, input := range request.Matches {
		// Build models.Player from proto PlayerData
		player1 := models.Player{
			Id:     *input.Player1.PlayerId,
			Name:   *input.Player1.PlayerName,
			Rating: *input.Player1.PlayerRating,
			RegId:  *input.Player1.RegId,
		}
		player2 := models.Player{
			Id:     *input.Player2.PlayerId,
			Name:   *input.Player2.PlayerName,
			Rating: *input.Player2.PlayerRating,
			RegId:  *input.Player2.RegId,
		}

		// Build models.Match (MatchId will be generated by repo, Status will be set by repo)
		match := models.Match{
			Player1Id: player1.Id,
			Player2Id: player2.Id,
		}
		if input.Fleet != nil {
			match.Fleet = *input.Fleet
		}

		// Call repo
		result, err := s.repo.SaveCreateMatch(ctx, match, player1, player2)
		if err != nil {
			logger.Debug("StartMatch: SaveCreateMatch failed", "error", err, "result", result)
			results = append(results, &pb.MatchCreationResult{
				MatchId:             nil,
				Player1FailResponse: pb.PlayerFailResponse_PLAYER_FAIL_RESPONSE_REENTER,
				Player2FailResponse: pb.PlayerFailResponse_PLAYER_FAIL_RESPONSE_REENTER,
			})
			continue
		}

		// Success
		res := &pb.MatchCreationResult{
			MatchId: result.MatchId,
		}
		if result.Fail1 != nil {
			res.Player1FailResponse = mapFailResponse(*result.Fail1)
		}
		if result.Fail2 != nil {
			res.Player2FailResponse = mapFailResponse(*result.Fail2)
		}
		results = append(results, res)
	}

	return &pb.StartMatchResponse{Results: results}, nil
}

func (s *matchServiceImpl) GetMatch(ctx context.Context, request *pb.GetMatchRequest) (*pb.GetMatchResponse, error) {
	logger := logging.GetLogger(ctx)

	if err := validateGetMatchRequest(request); err != nil {
		logger.Debug("GetMatch: validation failed", "error", err)
		return nil, status.Error(codes.InvalidArgument, err.Error())
	}
	match, player1, player2, err := s.repo.GetMatchByPlayerId(ctx, *request.PlayerId)
	if err != nil {
		logger.Debug("GetMatch: GetMatchByPlayerId failed", "playerId", *request.PlayerId, "error", err)
		return nil, status.Errorf(codes.Internal, "failed to get match: %v", err)
	}
	if match == nil {
		logger.Debug("GetMatch: no match found for player", "playerId", *request.PlayerId)
		return &pb.GetMatchResponse{}, nil
	}
	switch match.Status {
	case models.Finished:
		logger.Debug("GetMatch: match finished, removing", "matchId", match.MatchId)
		if err := s.repo.RemoveMatch(ctx, match.MatchId); err != nil {
			logger.Debug("GetMatch: RemoveMatch failed", "matchId", match.MatchId, "error", err)
			return nil, status.Errorf(codes.Internal, "failed to remove finished match: %v", err)
		}
		return &pb.GetMatchResponse{}, nil
	case models.Initialising:
		fallthrough
	case models.Ongoing:
		// Query fleet manager for server connection
		req := &fmPb.GetServerRequest{
			MatchId: &match.MatchId,
		}
		resp, err := s.fmFactory.GetServer(ctx, req)
		if err != nil {
			logger.Debug("GetMatch: GetServer failed or no connection info", "matchId", match.MatchId, "error", err)
			return &pb.GetMatchResponse{}, nil
		}
		if resp == nil || resp.ConnectionInfo == nil {
			if match.Status == models.Initialising {
				logger.Info("Server not found while initializing. Skipping")
			} else {
				logger.Warn("GetMatch: server for ongoing match not found - clearing")
				if err := s.repo.RemoveMatch(ctx, match.MatchId); err != nil {
					logger.Warn("GetMatch: unable to remove absent ongoing match from redis", "error", err)
				}
			}
			return &pb.GetMatchResponse{}, nil
		}
		if match.Status == models.Initialising {
			if err := s.repo.SaveMatchStart(ctx, match.MatchId); err != nil {
				logger.Warn("Get match: unable to change initializing->ongoing", "error", err)
			}
		}
		return &pb.GetMatchResponse{
			ConnectionInfo: resp.ConnectionInfo,
			Player1Id:      &match.Player1Id,
			Player2Id:      &match.Player2Id,
		}, nil

	case models.Requested:
		if err := s.repo.SaveMatchInitialising(ctx, match.MatchId); err != nil {
			logger.Info("GetMatch: Unable to switch requested->initializing", "error", err)
			return &pb.GetMatchResponse{}, nil
		}
		// Prepare player annotations
		player1IdStr := strconv.FormatInt(player1.Id, 10)
		player1Name := player1.Name
		player1RatingStr := strconv.FormatInt(player1.Rating, 10)

		player2IdStr := strconv.FormatInt(player2.Id, 10)
		player2Name := player2.Name
		player2RatingStr := strconv.FormatInt(player2.Rating, 10)

		allocReq := &fmPb.AllocateRequest{
			Player1: &fmPb.PlayerAnnotations{
				Id:     &player1IdStr,
				Name:   &player1Name,
				Rating: &player1RatingStr,
			},
			Player2: &fmPb.PlayerAnnotations{
				Id:     &player2IdStr,
				Name:   &player2Name,
				Rating: &player2RatingStr,
			},
			FleetName: &match.Fleet,
			MatchId:   &match.MatchId,
		}
		allocResp, err := s.fmFactory.Allocate(ctx, allocReq)
		if err != nil || allocResp == nil || allocResp.ConnectionInfo == nil {
			logger.Debug("GetMatch: Allocate failed or no connection info", "matchId", match.MatchId, "error", err)
			if err := s.repo.CancelMatchInitializing(ctx, match.MatchId); err != nil {
				logger.Warn("Could not cancel init", "matchId", match.MatchId, "error", err)
			}
			return &pb.GetMatchResponse{}, nil
		}
		// Mark match as started
		if err := s.repo.SaveMatchStart(ctx, match.MatchId); err != nil {
			logger.Debug("GetMatch: SaveMatchStart failed", "matchId", match.MatchId, "error", err)
			return nil, status.Errorf(codes.Internal, "failed to update match status: %v", err)
		}
		if err := s.repo.SaveMatchStart(ctx, match.MatchId); err != nil {
			logger.Warn("Get match: unable to change initializing->ongoing", "error", err)
		}
		return &pb.GetMatchResponse{
			ConnectionInfo: allocResp.ConnectionInfo,
			Player1Id:      &match.Player1Id,
			Player2Id:      &match.Player2Id,
		}, nil

	default:
		logger.Debug("GetMatch: unknown match status", "matchId", match.MatchId, "status", match.Status)
		return &pb.GetMatchResponse{}, nil
	}
}

func (s *matchServiceImpl) EndMatch(ctx context.Context, request *pb.EndMatchRequest) (*pb.EndMatchResponse, error) {
	logger := logging.GetLogger(ctx)

	if err := validateEndMatchRequest(request); err != nil {
		logger.Debug("EndMatch: validation failed", "error", err)
		return nil, status.Error(codes.InvalidArgument, err.Error())
	}

	// Retrieve match and players by match id
	match, player1, player2, err := s.repo.GetMatchById(ctx, *request.MatchId)
	if err != nil {
		logger.Debug("EndMatch: GetMatchById failed", "matchId", *request.MatchId, "error", err)
		return &pb.EndMatchResponse{}, nil
	}
	if match == nil {
		logger.Debug("EndMatch: match not found", "matchId", *request.MatchId)
		return &pb.EndMatchResponse{}, nil
	}

	// Only ongoing matches can be ended
	if match.Status != models.Ongoing {
		logger.Debug("EndMatch: match not ongoing", "matchId", match.MatchId, "status", match.Status)
		return &pb.EndMatchResponse{}, nil
	}

	// Determine match outcome
	var historyResult v2Pb.MatchResult
	if request.WinnerId == nil {
		historyResult = v2Pb.MatchResult_MATCH_RESULT_DRAW
	} else {
		winnerId := *request.WinnerId
		switch winnerId {
		case player1.Id:
			historyResult = v2Pb.MatchResult_MATCH_RESULT_PLAYER1_WIN
		case player2.Id:
			historyResult = v2Pb.MatchResult_MATCH_RESULT_PLAYER2_WIN
		default:
			logger.Debug("EndMatch: winner_id does not match any player", "winnerId", winnerId, "player1Id", player1.Id, "player2Id", player2.Id)
			return nil, status.Error(codes.InvalidArgument, "winner_id does not match either player")
		}
	}

	// Prepare match history v2 request (SaveMatch handles both history and rating)
	nowMillis := time.Now().UnixMilli()
	p1Data := &v2Pb.ParticipantData{
		Id:     &player1.Id,
		Name:   &player1.Name,
		Rating: &player1.Rating,
	}
	p2Data := &v2Pb.ParticipantData{
		Id:     &player2.Id,
		Name:   &player2.Name,
		Rating: &player2.Rating,
	}

	matchData := &v2Pb.MatchData{
		Player1:      p1Data,
		Player2:      p2Data,
		Rounds:       request.Rounds,
		EndTimestamp: &nowMillis,
		MatchResult:  historyResult,
		MatchId:      &match.MatchId,
	}

	// Call v2 SaveMatch (handles both history and rating atomically)
	var saveResp *v2Pb.SaveMatchResponse
	var saveErr error
	var wg sync.WaitGroup
	wg.Add(1)
	go func() {
		defer wg.Done()
		saveResp, saveErr = s.mhsV2Factory.SaveMatch(ctx, &v2Pb.SaveMatchRequest{Match: matchData})
	}()
	wg.Wait()

	if saveErr != nil {
		logger.Debug("EndMatch: SaveMatch v2 error", "error", saveErr)
		return nil, status.Errorf(codes.Aborted, "failed to record match result: %v", saveErr)
	}

	// Mark match as finished in Redis
	if err := s.repo.SaveMatchFinish(ctx, match.MatchId); err != nil {
		logger.Debug("EndMatch: SaveMatchFinish failed", "matchId", match.MatchId, "error", err)
		return nil, status.Errorf(codes.Aborted, "failed to update match status: %v", err)
	}

	endResp := &pb.EndMatchResponse{}
	if saveResp != nil {
		if saveResp.Player1Rating != nil {
			endResp.NewRating_1 = saveResp.Player1Rating.DisplayValue
		}
		if saveResp.Player2Rating != nil {
			endResp.NewRating_2 = saveResp.Player2Rating.DisplayValue
		}
	}
	return endResp, nil
}

func (s *matchServiceImpl) CancelMatch(ctx context.Context, request *pb.CancelMatchRequest) (*pb.CancelMatchResponse, error) {
	logger := logging.GetLogger(ctx)

	if err := validateCancelMatchRequest(request); err != nil {
		logger.Debug("CancelMatch: validation failed", "error", err)
		return nil, status.Error(codes.InvalidArgument, err.Error())
	}

	match, _, _, err := s.repo.GetMatchById(ctx, *request.MatchId)
	if err != nil || match == nil {
		logger.Debug("CancelMatch: match not found or error", "matchId", *request.MatchId, "error", err)
		return &pb.CancelMatchResponse{}, nil
	}

	if err := s.repo.RemoveMatch(ctx, match.MatchId); err != nil {
		logger.Debug("CancelMatch: RemoveMatch failed", "matchId", match.MatchId, "error", err)
		return nil, status.Errorf(codes.Aborted, "failed to remove match: %v", err)
	}

	return &pb.CancelMatchResponse{}, nil
}

func (s *matchServiceImpl) RenewMatch(ctx context.Context, request *pb.RenewMatchRequest) (*pb.RenewMatchResponse, error) {
	logger := logging.GetLogger(ctx)

	if err := validateRenewMatchRequest(request); err != nil {
		logger.Debug("RenewMatch: validation failed", "error", err)
		return nil, status.Error(codes.InvalidArgument, err.Error())
	}

	newMatchId, err := s.repo.RestartMatch(ctx, *request.MatchId)
	if err != nil {
		logger.Debug("RenewMatch: RestartMatch failed", "matchId", *request.MatchId, "error", err)
		return nil, status.Errorf(codes.Aborted, "failed to renew match: %v", err)
	}

	return &pb.RenewMatchResponse{MatchId: &newMatchId}, nil
}
